### ISSUE TITLE
incorrectly mapped data-prepper service volume for trace analysis 

### ISSUE THREAD

**Issue by besha100** [opensearch-project/opentelemetry-demo#102]
# Bug Report

Which version of the demo you are using? (please provide either a specific
[59ec0e9](https://github.com/opensearch-project/opentelemetry-demo/commit/59ec0e9b95517a9e6d15a0db34bf677b1381ff51)

## Symptom

In the docker-compose, data-prepper service is using the default pipelines.yml volume for the otel_logs_source. This is mismapped to trace_analytics_no_ssl_2x.yml file in the pod [here](https://github.com/opensearch-project/opentelemetry-demo/blob/59ec0e9b95517a9e6d15a0db34bf677b1381ff51/docker-compose.yml#L758C1-L759C1). 

    volumes:
      - ./src/dataprepper/pipelines.yaml:/usr/share/data-prepper/pipelines/trace_analytics_no_ssl_2x.yml

This needs to be fixed with the below volume instead
    volumes:
      - ./src/dataprepper/trace_analytics_no_ssl_2x.yml:/usr/share/data-prepper/pipelines/trace_analytics_no_ssl_2x.yml
      - ./src/dataprepper/pipelines.yaml:/usr/share/data-prepper/pipelines/pipelines.yaml

**What is the expected behavior?**

The expected behavior is to have traces also shown up in data-prepper data source with service-map, trace error, high latency, etc

**What is the actual behavior?**

Only Traces via Jeager is available.

## Reproduce

```
git clone https://github.com/opensearch-project/opentelemetry-demo.git
cd opentelemetry-demo
docker compose up -d
```
Then check traces observability plugin > Data prepper data source

**Comment by YANG-DB** [comment]
thanks for your help
